### ISSUE TITLE
test_batch.py: error: unrecognized arguments: --trainer UNIT

### ISSUE THREAD

**Issue by Abbsalehi** [mhaut/UIMG2DSM#1]
Dear, 

Your help would be appreciated. I wanna run your published code, but I'm facing such this error. How can I solve the error?  I'm trying to run your first suggestion to execute your code on terminal. I'm running this below command as you said in README.md:

_python test_batch.py --trainer UNIT --config ./configs/unit_img2dsm_folder.yaml --a2b 1 --input ./dataset/testA/ --output_folder ./results/outputs --checkpoint ./outputs/unit_img2dsm_folder/checkpoints/gen_00700000.pt_

but unfortunately, I'm facing the mentioned error:
**error:** _unrecognized arguments: --trainer UNIT_

**Comment by mhaut** [comment]
Dear @Abb1989 

I have updated the README now. Please, let me know if you have run the code ok or if you have had problems/doubts.

best

**Comment by Abbsalehi** [comment]
> Dear @Abb1989
> 
> I have updated the README now. Please, let me know if you have run the code ok or if you have had problems/doubts.
> 
> best

Thank you for your kind response. I will inform you here if there are problems.
