### ISSUE TITLE
Prediction of the trained model 

### ISSUE THREAD

**Issue by Abbsalehi** [mhaut/UIMG2DSM#2]
Dear, 

How can I predict an RGB input image through this trained model "UIMG2DSM"? is there any python script for prediction purpose? Is it possible to use the trained model to predict a DSM from the RGB input image? how much pixel size would be suitable for the RGB input image? Your response would be appreciated. 

Thanks,
Abbas Salehi

**Comment by mhaut** [comment]
https://github.com/mhaut/UIMG2DSM/blob/master/README.md

**Comment by Abbsalehi** [comment]
> https://github.com/mhaut/UIMG2DSM/blob/master/README.md

My mean is that, how can i write prediction python code using the trained model with one another RGB input image？could you help me to write?

**Comment by Abbsalehi** [comment]
Dear Mhaut, 

How can I contact you? Do you have an email address?
